const words=["Car", "bike", "building", "laptop", "phone", "well", "pond", "medicine", "water", "bottle", "cap", "dog", "cat", 
"puppy", "remote", "camera", "mic", "mouse", "keyboard", "YouTube", "earphone", "Microsoft", "google", "disk", "tie", "watch", 
"speaker", "bedsheet", "pillow", "trimmer", "plate", "wire", "pen", "pencil", "eraser", "toothbrush", "LED", "monitor", "bulb", 
"fan", "cooler", "chair", "table", "light", "nothing", "black", "white", "china", "India", "moon", "sun", "moonlight", "belt", 
"dress", "MacBook", "iPhone", "press", "magazine", "newspaper", "pizza", "burger", "sandwich", "McDonald", "window", "Samsung", 
"wallet", "airplane", "helicopter", "temperature", "goggles", "android", "apple", "banana", "orange", "mango", "pomegranate", 
"ladder", "perfume", "comb", "road", "track", "hell", "heaven", "devil", "god", "traffic", "lock", "avengers", "superman", "batman", 
"silver", "gold", "diamond", "platinum", "bitcoin", "stars", "smile", "pimples", "tears", "eyes", "eyebrow", "cycle", "leg", 
"armpit", "armour", "shield", "umbrella", "parrot", "peacock", "gym", "coin", "socket", "gun", "chalk", "duster", "tree", "garden", 
"lemon", "carrot", "rabbit", "unicorn", "elephant", "rainbow", "engine", "jet", "strawberry", "eclipse", "chandelier", "ketchup", 
"beehive", "wreath", "waffles", "bubble", "whistle", "snowball", "bouquet", "headphones", "fireworks", "igloo", "summer", "cupcake", 
"bruise", "fog", "crust", "battery", "brush", "Paris", "beach", "mountains", "train", "ambulance", "giraffe", "scorpion", "lion", 
"dolphin", "frog", "panda", "SpongeBob", "pirate", "Olympic", "sunburn", "sunscreen", "sugarcane", "paper", "dice", "timer", "egg", 
"nose", "ear", "lamp", "butterfly", "bucket", "stairs", "shoes", "volleyball", "mailbox", "night", "starfish", "toothpaste", 
"mirror", "peanut", "bread", "fork", "knife", "spoon", "cylinder", "brain", "tricycle", "slipper", "dragon", "piano", "guitar", 
"trumpet", "music", "telescope", "microscope", "hockey", "cricket", "space", "stethoscope", "mask", "zombie", "hair", "chest", 
"shoulder", "blackberry", "notebook", "coffee", "thermos", "clipboard", "chocolate", "paperwork", "sandcastle", "bamboo", "hammer", 
"tennis", "bridge", "bubblegum", "pancakes", "watermelon", "baseball", "bat", "ball", "kiss", "jellyfish", "jelly", "bats", "basket", 
"goosebumps", "platypus", "smoke", "blanket", "seaweed", "worm", "leaf", "plane", "cow", "house", "paintings", "bowl", "cushion", 
"sofa", "shirt", "schoolbag", "towel", "hat", "scarf", "bandage", "printer", "recylce", "trash", "ninja", "pumpkin", "vampire", 
"noodles", "whiteboard", "thunderstorm", "chalkboard", "zigzag", "thermometer", "Ferrari", "BMW", "spiderweb", "hammock", "bacteria", 
"pyramid", "square", "rectangle", "circle", "cube", "cuboid", "cone", "sphere", "flame", "forest", "antenna", "wallpaper", "monkey", 
"leopard", "chicken", "snake", "alligator", "hamster", "mosquito", "sheep", "shark", "whale", "zebra", "pole", "decade", "century", 
"millennium", "planet", "winter", "hamburger", "shovel", "charger", "tea", "river", "himalayas"] ;

module.exports = words;